<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Test Remove Location"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="3.506">
  <properties />
            <testcase name="testRemoveLocationSelenium" time="3.506" classname="org.roommanager.test.admin.location.RemoveLocation">
                <failure type="org.junit.ComparisonFailure"
                  message="expected:&lt;[Location LocationTest01 sucessfully removed]&gt; but was:&lt;[]&gt;"
              >
<![CDATA[org.junit.ComparisonFailure: expected:<[Location LocationTest01 sucessfully removed]> but was:<[]>
  org.junit.Assert.assertEquals(Assert.java:115)
  org.junit.Assert.assertEquals(Assert.java:144)
  org.roommanager.test.admin.location.RemoveLocation.testRemoveLocationSelenium(RemoveLocation.java:101)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:771)
  org.testng.TestRunner.run(TestRunner.java:621)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
  org.testng.SuiteRunner.run(SuiteRunner.java:259)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
  org.testng.TestNG.run(TestNG.java:1033)
  org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
